#!/usr/bin/env bash
# Script to setup an nginx server
index_file=/var/www/html/index.nginx-debian.html
default_web=/etc/nginx/sites-available/default
sudo apt update
sudo apt install nginx -y
echo "Hello World!" | sudo tee $index_file &&
sudo chmod 644 $index_file
sudo chmod a+w $default_web &&
sudo sed -i '/server_name _;/a\\n\tlocation /redirect_me {\n\t\trewrite ^/redirect_me https://google.com permanent;\n\t}\n' $default_web &&
sudo chmod 644 $default_web &&
sudo service nginx restart
